const state = {
  currentView: 'home',
  timelineFilter: 'All',
  data: null,
  error: null
};

const $ = (selector) => document.querySelector(selector);

async function init() {
  renderClock();
  setInterval(renderClock, 60000);
  renderLoading();
  try {
    const response = await fetch('./data/dashboard.json', { cache: 'no-store' });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    state.data = await response.json();
    render();
  } catch (error) {
    state.error = error;
    renderError(error);
  }
}

function renderClock() {
  $('#clock').textContent = new Date().toLocaleString('fr-CH', {
    weekday: 'short', hour: '2-digit', minute: '2-digit', day: '2-digit', month: 'short'
  });
}

function renderLoading() {
  $('#nav').innerHTML = '<button class="active"><span>Loading</span><small>local data</small></button>';
  $('#kpi-grid').innerHTML = Array.from({ length: 6 }, () => `
    <article class="kpi-card skeleton-card">
      <p class="eyebrow">Loading</p>
      <div class="value">--</div>
      <div class="delta">Refreshing local sources</div>
    </article>
  `).join('');
  $('#view-content').innerHTML = `
    <section class="panel">
      <div class="panel-header">
        <div>
          <p class="eyebrow">Booting</p>
          <h3>Mission Control is loading local data</h3>
        </div>
      </div>
      <p class="muted">Reading JSON generated by refresh_data.py.</p>
    </section>
  `;
}

function renderError(error) {
  $('#nav').innerHTML = '<button class="active"><span>Setup needed</span><small>serve locally</small></button>';
  $('#view-title').textContent = 'Mission Control';
  $('#kpi-grid').innerHTML = '';
  $('#view-content').innerHTML = `
    <section class="panel">
      <div class="panel-header">
        <div>
          <p class="eyebrow">Data unavailable</p>
          <h3>Local JSON could not be loaded</h3>
        </div>
        <span class="tag blocked">Fix needed</span>
      </div>
      <p class="card-meta">${escapeHtml(error.message || String(error))}</p>
      <div class="stack">
        <article class="issue-card">
          <p class="card-title">1. Refresh the data</p>
          <p class="card-meta">python3 refresh_data.py</p>
        </article>
        <article class="issue-card">
          <p class="card-title">2. Serve the folder locally</p>
          <p class="card-meta">python3 -m http.server 8080</p>
        </article>
        <article class="issue-card">
          <p class="card-title">3. Open the app via HTTP</p>
          <p class="card-meta">http://localhost:8080</p>
        </article>
      </div>
    </section>
  `;
}

function renderNav() {
  const data = state.data;
  $('#nav').innerHTML = data.views.map(view => `
    <button class="${state.currentView === view.id ? 'active' : ''}" data-view="${view.id}">
      <span>${view.label}</span>
      <small>${view.hint}</small>
    </button>
  `).join('');

  $('#nav').querySelectorAll('button').forEach(btn => {
    btn.addEventListener('click', () => {
      state.currentView = btn.dataset.view;
      render();
    });
  });
}

function render() {
  const data = state.data;
  if (!data) return renderLoading();

  renderNav();
  renderSidebarMeta(data.meta);

  $('#kpi-grid').innerHTML = data.kpis.map(kpi => `
    <article class="kpi-card">
      <p class="eyebrow">${escapeHtml(kpi.label)}</p>
      <div class="value">${escapeHtml(kpi.value)}</div>
      <div class="delta">${escapeHtml(kpi.delta)}</div>
    </article>
  `).join('');

  const title = data.views.find(v => v.id === state.currentView)?.label || 'Mission Control';
  $('#view-title').textContent = title;

  const container = $('#view-content');
  container.innerHTML = '';
  const template = document.getElementById(`${state.currentView}-template`);
  container.appendChild(template.content.cloneNode(true));

  const renderers = {
    home: renderHome,
    agents: renderAgents,
    tasks: renderTasks,
    projects: renderProjects,
    decisions: renderDecisions,
    timeline: renderTimeline
  };
  renderers[state.currentView]();
}

function renderSidebarMeta(meta = {}) {
  const statusPill = document.querySelector('.status-pill.live');
  if (statusPill) statusPill.textContent = meta.statusLabel || 'Live local data';

  const sidebarTitle = document.querySelector('.sidebar-card h3');
  const sidebarNote = document.querySelector('.sidebar-card .muted');
  const sourceList = meta.sources || [];

  if (sidebarTitle) sidebarTitle.textContent = meta.focusOfDay || 'Unknown focus';
  if (sidebarNote) {
    sidebarNote.textContent = `${meta.focusNote || 'No focus note.'} Last refresh: ${meta.generatedAt || 'unknown'}`;
  }

  let sourceBlock = document.getElementById('source-list');
  if (!sourceBlock) {
    sourceBlock = document.createElement('div');
    sourceBlock.id = 'source-list';
    sourceBlock.className = 'stack source-list';
    document.querySelector('.sidebar-card').appendChild(sourceBlock);
  }
  sourceBlock.innerHTML = sourceList.slice(0, 4).map(source => `
    <div class="small muted">${escapeHtml(source)}</div>
  `).join('');
}

function renderHome() {
  const data = state.data;
  const lanes = [
    ['Now', data.lanes.now],
    ['Next', data.lanes.next],
    ['Later', data.lanes.later]
  ];

  $('#priority-lanes').innerHTML = lanes.map(([label, items]) => `
    <div class="lane">
      <h4>${label}</h4>
      <div class="stack">
        ${(items || []).map(item => `
          <article class="lane-card">
            <p class="card-title">${escapeHtml(item.title)}</p>
            <div class="card-meta">${escapeHtml(item.project)} · ${escapeHtml(item.owner)}</div>
            <div class="card-foot">Deadline: ${escapeHtml(item.deadline)}</div>
            <div class="tag ${statusClass(item.status)}">${escapeHtml(item.status)}</div>
          </article>
        `).join('') || '<div class="small muted">No items</div>'}
      </div>
    </div>
  `).join('');

  $('#alerts-list').innerHTML = renderCollection(data.alerts, alert => `
    <article class="alert-card">
      <p class="card-title">${escapeHtml(alert.title)}</p>
      <p class="card-meta">${escapeHtml(alert.text)}</p>
    </article>
  `);

  $('#decision-panel').innerHTML = renderCollection(data.decisions, item => `
    <article class="decision-card">
      <div class="panel-header">
        <div>
          <p class="card-title">${escapeHtml(item.title)}</p>
          <p class="card-meta">${escapeHtml(item.impact)} · ${escapeHtml(item.deadline)}</p>
        </div>
        <span class="tag blocked">Decision</span>
      </div>
      <p>${escapeHtml(item.recommendation)}</p>
      <div class="card-foot">Options: ${escapeHtml((item.options || []).join(' / '))}</div>
    </article>
  `);

  $('#health-matrix').innerHTML = `
    <table class="health-table">
      <thead><tr><th>Projet</th><th>Priorité</th><th>Santé</th><th>Owner</th><th>Milestone</th></tr></thead>
      <tbody>
        ${data.projects.map(project => `
          <tr>
            <td>${escapeHtml(project.name)}</td>
            <td>${escapeHtml(project.priority)}</td>
            <td><span class="health-dot ${healthClass(project.health)}"></span>${escapeHtml(project.health)}</td>
            <td>${escapeHtml(project.owner)}</td>
            <td>${escapeHtml(project.milestone)}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;

  $('#impact-grid').innerHTML = data.impact.map(item => `
    <div class="metric-row">
      <div>
        <p class="eyebrow">${escapeHtml(item.label)}</p>
        <div class="small">${escapeHtml(item.detail)}</div>
      </div>
      <strong>${escapeHtml(item.value)}</strong>
    </div>
  `).join('');

  $('#timeline-preview').innerHTML = data.timeline.slice(0, 5).map(renderTimelineItem).join('');
}

function renderAgents() {
  const data = state.data;
  $('#agents-grid').innerHTML = renderCollection(data.agents, agent => `
    <article class="agent-card">
      <div class="panel-header">
        <div>
          <p class="card-title">${escapeHtml(agent.name)}</p>
          <p class="card-meta">${escapeHtml(agent.role)}</p>
        </div>
        <span class="tag ${statusClass(agent.status)}">${escapeHtml(agent.status)}</span>
      </div>
      <p><strong>Mission:</strong> ${escapeHtml(agent.mission)}</p>
      <p class="muted"><strong>Dernier output:</strong> ${escapeHtml(agent.output)}</p>
      <div class="metric-row"><span>Source</span><strong>${escapeHtml(agent.source || 'unknown')}</strong></div>
    </article>
  `);

  $('#agent-metrics').innerHTML = data.agents.map(agent => `
    <div class="metric-row">
      <div>
        <strong>${escapeHtml(agent.name)}</strong>
        <div class="small">${escapeHtml(agent.throughput)} · escalations ${escapeHtml(agent.escalations)}</div>
      </div>
      <span class="tag ${statusClass(agent.status)}">${escapeHtml(agent.blockers)}</span>
    </div>
  `).join('');

  $('#agent-issues').innerHTML = renderCollection(
    data.agents.filter(agent => agent.blockers && agent.blockers !== 'unknown'),
    agent => `<article class="issue-card">${escapeHtml(agent.name)}: ${escapeHtml(agent.blockers)}</article>`
  );
}

function renderTasks() {
  const data = state.data;
  const columns = ['Inbox', 'Ready', 'In progress', 'Waiting', 'Blocked', 'Done'];
  $('#kanban').innerHTML = columns.map(column => `
    <div class="kanban-column">
      <h4>${column}</h4>
      ${data.tasks.filter(task => normalizeTaskStatus(task.status) === column).map(task => `
        <article class="task-chip">
          <p class="card-title">${escapeHtml(task.title)}</p>
          <div class="card-meta">${escapeHtml(task.project)} · ${escapeHtml(task.owner)}</div>
          <div class="card-foot">${escapeHtml(task.priority)} · ${escapeHtml(task.deadline)}</div>
        </article>
      `).join('') || '<div class="small muted">No items</div>'}
    </div>
  `).join('');

  $('#task-table').innerHTML = data.tasks.map(task => `
    <tr>
      <td>${escapeHtml(task.title)}</td>
      <td>${escapeHtml(task.project)}</td>
      <td>${escapeHtml(task.owner)}</td>
      <td>${escapeHtml(task.priority)}</td>
      <td>${escapeHtml(task.deadline)}</td>
      <td>${escapeHtml(task.next)}</td>
    </tr>
  `).join('');

  $('#blocked-tasks').innerHTML = renderCollection(
    data.tasks.filter(task => task.blocker),
    task => `
      <article class="issue-card">
        <p class="card-title">${escapeHtml(task.title)}</p>
        <p class="card-meta">Reason: ${escapeHtml(task.blocker)}</p>
        <div class="card-foot">Who acts: ${escapeHtml(task.owner)} · Since: ${escapeHtml(task.since || 'unknown')}</div>
      </article>
    `,
    '<article class="issue-card">No explicit blockers found in the local task sources.</article>'
  );
}

function renderProjects() {
  const data = state.data;
  $('#projects-grid').innerHTML = renderCollection(data.projects, project => `
    <article class="project-card">
      <div class="panel-header">
        <div>
          <p class="card-title">${escapeHtml(project.name)}</p>
          <p class="card-meta">${escapeHtml(project.phase)}</p>
        </div>
        <span class="tag ${projectTag(project.health)}">${escapeHtml(project.health)}</span>
      </div>
      <p><strong>Priority:</strong> ${escapeHtml(project.priority)}</p>
      <p><strong>Value:</strong> ${escapeHtml(project.revenue || 'unknown')}</p>
      <p class="muted"><strong>Milestone:</strong> ${escapeHtml(project.milestone)}</p>
    </article>
  `);

  $('#value-table').innerHTML = data.projects.map(project => `
    <tr>
      <td>${escapeHtml(project.name)}</td>
      <td>${escapeHtml(project.revenue || 'unknown')}</td>
      <td>${escapeHtml(project.potential || 'unknown')}</td>
      <td>${escapeHtml(project.risk || 'unknown')}</td>
      <td>${escapeHtml(project.effort || 'unknown')}</td>
    </tr>
  `).join('');

  $('#project-details').innerHTML = renderCollection(data.projects, project => `
    <article class="issue-card">
      <p class="card-title">${escapeHtml(project.name)}</p>
      <p class="card-meta">Goal: ${escapeHtml(project.goal || 'unknown')}</p>
      <div class="card-foot">Next decision: ${escapeHtml(project.next_step || 'unknown')}</div>
    </article>
  `);
}

function renderDecisions() {
  const data = state.data;
  $('#approval-inbox').innerHTML = renderCollection(data.approvals, approval => `
    <article class="approval-card">
      <div class="panel-header">
        <div>
          <p class="card-title">${escapeHtml(approval.item)}</p>
          <p class="card-meta">${escapeHtml(approval.type)} · ${escapeHtml(approval.urgency)} · ${escapeHtml(approval.deadline)}</p>
        </div>
        <span class="tag ${approval.overdue ? 'blocked' : 'waiting'}">${approval.overdue ? 'Overdue' : 'Pending'}</span>
      </div>
      <p>${escapeHtml(approval.context)}</p>
      <p class="muted"><strong>Reco:</strong> ${escapeHtml(approval.recommendation)}</p>
      <div class="small muted">Source: ${escapeHtml(approval.source || 'unknown')}</div>
    </article>
  `);

  $('#overdue-approvals').innerHTML = renderCollection(
    data.approvals.filter(item => item.overdue),
    approval => `
      <article class="issue-card">
        <p class="card-title">${escapeHtml(approval.item)}</p>
        <p class="card-meta">${escapeHtml(approval.impact)}</p>
        <div class="card-foot">Late since: ${escapeHtml(approval.deadline)}</div>
      </article>
    `,
    '<article class="issue-card">No overdue approvals found in the current local dataset.</article>'
  );
}

function renderTimeline() {
  const data = state.data;
  const filters = ['All', ...new Set(data.timeline.map(item => item.type))];
  $('#filters').innerHTML = filters.map(filter => `
    <button class="filter-chip ${state.timelineFilter === filter ? 'active' : ''}" data-filter="${filter}">${filter}</button>
  `).join('');

  $('#filters').querySelectorAll('button').forEach(btn => {
    btn.addEventListener('click', () => {
      state.timelineFilter = btn.dataset.filter;
      renderTimeline();
    });
  });

  const items = state.timelineFilter === 'All'
    ? data.timeline
    : data.timeline.filter(item => item.type === state.timelineFilter);

  $('#full-timeline').innerHTML = renderCollection(items, renderTimelineItem, '<article class="issue-card">No timeline events for this filter.</article>');
}

function renderTimelineItem(item) {
  return `
    <article class="timeline-item">
      <div class="time">${escapeHtml(item.time)} · ${escapeHtml(item.actor)} · ${escapeHtml(item.project)}</div>
      <p class="card-title">${escapeHtml(item.type)}</p>
      <div class="card-meta">${escapeHtml(item.text)}</div>
    </article>
  `;
}

function renderCollection(items, mapper, fallback = '<article class="issue-card">No data available.</article>') {
  if (!items || !items.length) return fallback;
  return items.map(mapper).join('');
}

function normalizeTaskStatus(status) {
  const value = (status || '').toLowerCase();
  if (value === 'done') return 'Done';
  if (value === 'blocked') return 'Blocked';
  if (value === 'waiting') return 'Waiting';
  if (value === 'in progress') return 'In progress';
  if (value === 'ready') return 'Ready';
  if (value === 'inbox') return 'Inbox';
  return 'Inbox';
}

function statusClass(status = '') {
  const value = status.toLowerCase();
  if (value.includes('block')) return 'blocked';
  if (value.includes('wait')) return 'waiting';
  if (value.includes('run') || value.includes('progress') || value.includes('live')) return 'running';
  if (value.includes('done') || value.includes('track') || value.includes('ready')) return 'ontrack';
  if (value.includes('unknown')) return 'risk';
  return 'risk';
}

function healthClass(health = '') {
  return health.toLowerCase().replace(/\s+/g, '-');
}

function projectTag(health = '') {
  const h = health.toLowerCase();
  if (h.includes('blocked')) return 'blocked';
  if (h.includes('risk')) return 'waiting';
  if (h.includes('waiting')) return 'risk';
  if (h.includes('unknown')) return 'risk';
  return 'ontrack';
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, char => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;'
  })[char]);
}

init();
